name: Deploy GuestbookApp #워크플로워 이름 큰 의미는 없음

on:
   workflow_dispatch:

#on:                       #이벤트 정의
#  push:
#    branches:
#      - master # master 깃허브에 push가 되면 적용

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build . -t odioni/guestbook:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push odioni/guestbook:latest
        
  SSH:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull odioni/guestbook:latest
            sudo docker stop guestbook || true
            sudo docker rm guestbook || true
            sudo docker run -d --name guestbook -p 9000:9000 odioni/guestbook:latest